import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    routes: [
      {
        id: 'RT-001',
        name: 'Shanghai → Los Angeles',
        origin: { lat: 31.23, lng: 121.47, label: 'Shanghai' },
        destination: { lat: 33.94, lng: -118.41, label: 'Los Angeles' },
        risk: 'HIGH',
        riskScore: 87,
        delay: '+2.3 days',
        costImpact: '+12%',
        cause: 'Typhoon Mawar — South China Sea',
        suggestedReroute: 'Via Cape of Good Hope (+4 days, -8% cost risk)',
        status: 'DELAYED',
        cargo: '4,200 TEU',
        vessel: 'MV Pacific Horizon',
      },
      {
        id: 'RT-002',
        name: 'Rotterdam → New York',
        origin: { lat: 51.92, lng: 4.48, label: 'Rotterdam' },
        destination: { lat: 40.68, lng: -74.04, label: 'New York' },
        risk: 'MEDIUM',
        riskScore: 52,
        delay: '+0.8 days',
        costImpact: '+4%',
        cause: 'North Atlantic congestion',
        suggestedReroute: 'Standard route — monitoring',
        status: 'ON_TIME',
        cargo: '2,800 TEU',
        vessel: 'MV Atlantic Bridge',
      },
      {
        id: 'RT-003',
        name: 'Singapore → Dubai',
        origin: { lat: 1.35, lng: 103.82, label: 'Singapore' },
        destination: { lat: 25.27, lng: 55.30, label: 'Dubai' },
        risk: 'LOW',
        riskScore: 18,
        delay: '0 days',
        costImpact: '0%',
        cause: 'None',
        suggestedReroute: 'N/A',
        status: 'ON_TIME',
        cargo: '1,600 TEU',
        vessel: 'MV Indian Express',
      },
      {
        id: 'RT-004',
        name: 'Tokyo → Vancouver',
        origin: { lat: 35.68, lng: 139.69, label: 'Tokyo' },
        destination: { lat: 49.28, lng: -123.12, label: 'Vancouver' },
        risk: 'MEDIUM',
        riskScore: 64,
        delay: '+1.1 days',
        costImpact: '+7%',
        cause: 'Port congestion at Vancouver',
        suggestedReroute: 'Divert to Seattle (+0.5 days)',
        status: 'AT_RISK',
        cargo: '3,100 TEU',
        vessel: 'MV Nippon Star',
      },
      {
        id: 'RT-005',
        name: 'Hamburg → Santos',
        origin: { lat: 53.55, lng: 9.99, label: 'Hamburg' },
        destination: { lat: -23.96, lng: -46.33, label: 'Santos' },
        risk: 'HIGH',
        riskScore: 78,
        delay: '+3.1 days',
        costImpact: '+15%',
        cause: 'Dockworkers strike — Santos port',
        suggestedReroute: 'Hold at Canary Islands, await resolution',
        status: 'DELAYED',
        cargo: '2,200 TEU',
        vessel: 'MV South Atlantic',
      },
    ],
    riskZones: [
      { lat: 22.0, lng: 115.0, radius: 500, risk: 'HIGH', label: 'South China Sea — Typhoon Zone' },
      { lat: -24.0, lng: -46.0, radius: 200, risk: 'HIGH', label: 'Santos Port — Strike' },
      { lat: 49.0, lng: -123.5, radius: 150, risk: 'MEDIUM', label: 'Vancouver — Congestion' },
    ],
    vehicles: [
      { id: 'V-001', routeId: 'RT-001', progress: 0.35, type: 'vessel' },
      { id: 'V-002', routeId: 'RT-002', progress: 0.72, type: 'vessel' },
      { id: 'V-003', routeId: 'RT-003', progress: 0.55, type: 'vessel' },
      { id: 'V-004', routeId: 'RT-004', progress: 0.21, type: 'vessel' },
      { id: 'V-005', routeId: 'RT-005', progress: 0.48, type: 'vessel' },
    ],
    summary: {
      totalRoutes: 847,
      activeShipments: 12400,
      highRiskCount: 42,
      avgDelay: '+1.2 days',
    },
  });
}
